Repository DeveloperAcademy-POSTECH/2025-C4-M1-CodePlay, pull requests merged in 2025-09, with the labels that each got.

#122 [FEAT] 카메라 진입 시 코치마크 오버레이 기능 추가
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/CoachMarkView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/CameraLiveTextView.swift
  Projects/CodePlay/CodePlay/Resources/drag.json
Labels: 🫡 Kwangro, ✨ Feat

#128 [REFACTOR] 아키텍쳐 구조 리펙토링
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/DIContainer/MainSceneDIContainer.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportPlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/ExportPlaylistViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/FestivalCheckViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/ViewModel/AppleMusicConnectViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/ViewModel/PosterViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CachedAsyncImage.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Enums.swift
Labels: ♻ Refactor

#132 [FIX] MadePlaylistView에서 생성된 플레이리스트 정렬 순서 유지해서 내보내기
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/SelectArtistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/ExportPlaylistViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
Labels: 🧠 Yan, 🐛 Fix

#135 [FIX] MadePlaylistView로 되돌아가는 네비게이션 이슈 해결
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/SelectArtistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
Labels: 🧠 Yan, 🐛 Fix
