Repository DeveloperAcademy-POSTECH/2025-C4-M1-CodePlay, pull requests merged in 2025-07, with the labels that each got.

#36 [REFACTOR] 라이센스 및 musicKit 로직 리펙토링
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/AppDelegate.swift
  Projects/CodePlay/CodePlay/Application/AppFlowCoordinator.swift
  Projects/CodePlay/CodePlay/Application/CodePlayApp.swift
  Projects/CodePlay/CodePlay/Application/DIContainer/AppComponent.swift
  Projects/CodePlay/CodePlay/Application/DIContainer/AppDIContainer.swift
  Projects/CodePlay/CodePlay/Application/DIContainer/MainSceneDIContainer.swift
  Projects/CodePlay/CodePlay/Application/RootDependency.swift
  Projects/CodePlay/CodePlay/Data/Network/DataMapping.swift
  Projects/CodePlay/CodePlay/Info.plist
  Projects/CodePlay/CodePlay/Presentation/Factory/LicenseFactory.swift
  Projects/CodePlay/CodePlay/Presentation/Factory/MainFactory.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportLoadingView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportPlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/ExportPlaylistViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/ViewModel/AppleMusicConnectViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/Root/MainView.swift
Labels: 🧠 Yan, ♻ Refactor

#51 [FEAT] 플레이리스트 HI-FI 구현
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/CodePlayApp.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/ExportPlaylistRepository.swift
  Projects/CodePlay/CodePlay/Domain/Models/PlaylistEntry.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportLoadingView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportPlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/ScanPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/Root/MainView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/ArtistCard.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/Background.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/LiquidGlass.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/UINavigationBar.swift
Labels: ✨ Feat

#53 [FEAT] mainView 선택된 이미지만 변환
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/OverlappingCardsView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/ViewModel/PosterItemModel.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/ArtistCard.swift
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/ArtistImg2.imageset/ArtistImg2.png
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/ArtistImg2.imageset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/ArtistImg3.imageset/ArtistImg3.png
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/ArtistImg3.imageset/Contents.json
Labels: 🫡 Kwangro, ✨ Feat

#41 [FEAT] 미리듣기 30초, 편집삭제
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/DIContainer/MainSceneDIContainer.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/MusicPlayerRepository.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/ScanPosterRepository.swift
  Projects/CodePlay/CodePlay/Domain/Models/MusicPlayerError.swift
  Projects/CodePlay/CodePlay/Domain/Usecases/MusicPlayerUseCase.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportPlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/ViewModel/PosterItemModel.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
Labels: 🫡 Kwangro, ✨ Feat

#57 [FIX] 머지 이후 MadePlaylistView 런타임 오류 에러 해결
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/PlaylistSectionView.swift
Labels: 👽 Elian, 🐛 Fix

#60 [Design] hi-fi 버튼 생성 및 에셋 폰트 오타 수정
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Info.plist
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/PrimitiveColor/Prime.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/PrimitiveColor/Second.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Fonts/Font.swift
Labels: 🍒 Cherry, 🔧 Chore

#61 [FIX] vision를 활용한 포스터 인식 뷰 개선
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/CameraLiveTextView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/ScanPosterView.swift
Labels: 🧠 Yan, 🐛 Fix

#63 [FIX] mainView 아티스트 카드 스와이핑 버그 해결
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/OverlappingCardsView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/ArtistCard.swift
Labels: 🫡 Kwangro, 🐛 Fix

#68 [FIX] playlist first 페이지 패딩, 미리듣기 30초 , 백그라운드, TiTle 오류 수정
  Projects/CodePlay/CodePlay/Domain/Interfaces/MusicPlayerRepository.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/OverlappingCardsView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/PrimitiveColor/Primary.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/PrimitiveColor/Secondary.colorset/Contents.json
Labels: 🫡 Kwangro, 🐛 Fix

#66 [FIX] 포스터 인식 수정 및 커스텀 카메라 UI 수정
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/CameraLiveTextView.swift
Labels: 🧠 Yan, 🐛 Fix

#70 [FIX] 메인뷰 아티스트 카드 클릭시 변경 오류
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/OverlappingCardsView.swift
Labels: 🫡 Kwangro, 🐛 Fix

#71 [FEAT] 페스티벌 확인 뷰 및 아티스트 선택 뷰 구현
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalCheckView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalSearchView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/SelectArtistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/FestivalBox.swift
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/PrimitiveColor/Blue10.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Fonts/Font.swift
Labels: 🧠 Yan, ✨ Feat

#72 [FEAT] ExportSuccessView UI 그리기 및 기능 설정
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
Labels: 🫡 Kwangro, ✨ Feat

#75 [FEAT] 네트워커 연결 및 API연동
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/AppDelegate.swift
  Projects/CodePlay/CodePlay/Data/Network/Base/BaseAPIService.swift
  Projects/CodePlay/CodePlay/Data/Network/Base/MoyaLoggerPlugin.swift
  Projects/CodePlay/CodePlay/Data/Network/Base/MoyaProvider.swift
  Projects/CodePlay/CodePlay/Data/Network/Base/NetworkResult.swift
  Projects/CodePlay/CodePlay/Data/Network/Base/NetworkService.swift
  Projects/CodePlay/CodePlay/Data/Network/Config.swift
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/FestInfoAPIService.swift
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/PostInfoTargetType.swift
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/Request/PostFestInfoTextRequestDTO.swift
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/Response/PostFestInfoResponseDTO.swift
  Projects/CodePlay/CodePlay/Data/Network/Notification/Error/NetworkError.swift
  Projects/CodePlay/CodePlay/Data/Network/Notification/NotificationAPIService.swift
  Projects/CodePlay/CodePlay/Data/Network/Notification/NotificationTargetType.swift
  Projects/CodePlay/CodePlay/Data/Network/Notification/Request/PostDeviceTokenRequestDTO.swift
  Projects/CodePlay/CodePlay/Data/Network/Notification/Response/PostDeviceTokenResponseDTO.swift
  Projects/CodePlay/CodePlay/Data/Network/Router/BaseTargetType.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/MusicPlayerRepository.swift
  Projects/CodePlay/CodePlay/Info.plist
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportSuccessView.swift
Labels: 👽 Elian, ✨ Feat

#79 [FEAT] Navigate 변경, 모델 및 불필요 코드 제거, 검색 API 도입
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/DIContainer/MainSceneDIContainer.swift
  Projects/CodePlay/CodePlay/Config.xcconfig
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/FestInfoAPIService.swift
  Projects/CodePlay/CodePlay/Data/Network/FestInfo/PostInfoTargetType.swift
  Projects/CodePlay/CodePlay/Data/Network/Router/BaseTargetType.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/ScanPosterRepository.swift
  Projects/CodePlay/CodePlay/Domain/Models/FestivalInfo.swift
  Projects/CodePlay/CodePlay/Domain/Models/Playlist.swift
  Projects/CodePlay/CodePlay/Domain/Models/SuggestTitles.swift
  Projects/CodePlay/CodePlay/Domain/Usecases/ScanPosterUseCase.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/ExportPlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalCheckView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalSearchView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/SelectArtistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/MadePlaylistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/CameraLiveTextView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/OverlappingCardsView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/ViewModel/PosterItemModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/ViewModel/PosterViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/LiquidGlass.swift
Labels: 👽 Elian, ✨ Feat

#86 [REFACTOR] API 호출 로직 클린아키텍쳐 적용해서 분리
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Application/DIContainer/MainSceneDIContainer.swift
  Projects/CodePlay/CodePlay/Data/Network/Repository/FestivalRepository.swift
  Projects/CodePlay/CodePlay/Domain/Usecases/FetchFestivalInfoUseCase.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalCheckView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalSearchView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/FestivalCheckViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/Root/MainView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/ArtistCard.swift
Labels: 🧠 Yan, ♻ Refactor

#88 [FEAT] 플레이리스트 생성 후 곡 삭제 기능 추가
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Domain/Interfaces/ExportPlaylistRepository.swift
  Projects/CodePlay/CodePlay/Domain/Interfaces/MusicPlayerRepository.swift
  Projects/CodePlay/CodePlay/Domain/Usecases/ExportPlaylistUseCase.swift
  Projects/CodePlay/CodePlay/Domain/Usecases/MusicPlayerUseCase.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/PlaylistSectionView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/ExportPlaylistViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/View/AppleMusicConnectView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/LicenseCheck/ViewModel/AppleMusicConnectViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/CameraLiveTextView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/CustomList.swift
Labels: 🫡 Kwangro, ✨ Feat

#92 [Design] Hi-fi 중간 병합
  Projects/CodePlay/CodePlay.xcodeproj/project.pbxproj
  Projects/CodePlay/CodePlay/Domain/Interfaces/ExportPlaylistRepository.swift
  Projects/CodePlay/CodePlay/Domain/Models/PlaylistEntry.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalCheckView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalNoneView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/FestivalSearchView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/FestivalCheck/SelectArtistView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/View/PlaylistSectionView.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/ExportPlaylist/ViewModel/FestivalCheckViewModel.swift
  Projects/CodePlay/CodePlay/Presentation/Scene/MainPosterView/View/MainPosterView.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/ArtistCard.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/BottomButton.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/LiquidGlass.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/ProgressBar.swift
  Projects/CodePlay/CodePlay/Presentation/Utils/Extensions/UINavigationBar.swift
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/3D img/Festivalfail.imageset/6.artist loading gray.png
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/3D img/Festivalfail.imageset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/LightDark Color/neu0.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/LightDark Color/neu1000.colorset/Contents.json
  Projects/CodePlay/CodePlay/Resources/Assets.xcassets/LightDark Color/neu200.colorset/Contents.json
Labels: 🍒 Cherry, 🔧 Chore
